; Tile index $000
.db $7F $00 $00 $7F $80 $7F $00 $80 $BF $40 $3F $BF $BF $40 $27 $BF $BB $44 $23 $BB $B3 $4C $33 $B3 $BF $40 $3F $BF $BF $40 $3F $BF
; Tile index $001
.db $FF $00 $00 $FF $00 $FF $00 $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $002
.db $FC $00 $00 $FC $02 $FD $00 $02 $FA $01 $FC $FA $FA $01 $CC $FA $F2 $09 $C4 $F2 $E2 $19 $E4 $E2 $FA $01 $FC $FA $FA $01 $FC $FA
; Tile index $003
.db $BF $40 $3F $BF $BF $40 $3F $BF $BF $40 $3F $BF $BF $40 $3F $BF $BF $40 $3F $BF $BF $40 $3F $BF $BF $40 $3F $BF $BF $40 $3F $BF
; Tile index $004
.db $FF $0F $F0 $FF $FF $18 $E0 $FF $F8 $10 $E7 $F8 $F8 $30 $C7 $F8 $F0 $20 $CF $F0 $F0 $60 $8F $F0 $E1 $40 $9E $E1 $E3 $41 $9C $E3
; Tile index $005
.db $FF $F0 $0F $FF $FF $18 $07 $FF $1F $08 $E7 $1F $1F $0C $E3 $1F $0F $04 $F3 $0F $0F $06 $F1 $0F $FF $02 $01 $FF $FF $FE $01 $FF
; Tile index $006
.db $FF $7E $81 $FF $FF $42 $81 $FF $E7 $42 $99 $E7 $E7 $42 $99 $E7 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6
; Tile index $007
.db $FF $7F $80 $FF $FF $40 $80 $FF $E0 $40 $9F $E0 $E0 $40 $9F $E0 $E0 $40 $9F $E0 $E0 $40 $9F $E0 $E7 $40 $98 $E7 $E7 $43 $98 $E7
; Tile index $008
.db $FF $FE $01 $FF $FF $02 $01 $FF $07 $02 $F9 $07 $07 $02 $F9 $07 $06 $03 $F8 $06 $06 $03 $F8 $06 $FE $03 $00 $FE $FE $FF $00 $FE
; Tile index $009
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $00A
.db $FA $01 $FC $FA $FA $01 $FC $FA $FA $01 $FC $FA $FA $01 $FC $FA $FA $01 $FC $FA $FA $01 $FC $FA $FA $01 $FC $FA $FA $01 $FC $FA
; Tile index $00B
.db $E3 $41 $9C $E3 $F3 $61 $8C $F3 $F1 $20 $CE $F1 $FC $30 $C3 $FC $DC $3C $C3 $DC $C7 $3F $C0 $C7 $E1 $1F $E0 $E1 $E0 $1F $E0 $E0
; Tile index $00C
.db $01 $FE $01 $01 $80 $FF $00 $80 $E0 $FF $00 $E0 $F8 $3F $00 $F8 $0F $0C $F3 $0F $27 $24 $DB $07 $D7 $D6 $29 $C7 $7F $FE $01 $43
; Tile index $00D
.db $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $C2 $43 $BC $C2 $DA $5B $A4 $C2 $DA $5B $A4 $C2 $FE $7F $80 $C2
; Tile index $00E
.db $C7 $82 $39 $C7 $C7 $82 $39 $C7 $CE $87 $30 $CE $CC $87 $30 $CC $8C $8F $70 $8C $A8 $AF $50 $88 $98 $9F $60 $98 $F1 $FE $01 $F1
; Tile index $00F
.db $E6 $C3 $18 $E6 $C6 $83 $38 $C6 $C6 $83 $38 $C6 $C6 $83 $38 $C6 $82 $83 $7C $82 $BA $BB $44 $82 $9A $9B $64 $82 $FE $FF $00 $C2
; Tile index $010
.db $00 $FF $00 $00 $FC $FF $00 $FC $FC $87 $00 $FC $CC $87 $30 $CC $CF $84 $33 $CF $FD $86 $01 $FD $FD $FE $01 $FD $81 $7E $81 $81
; Tile index $011
.db $C6 $83 $38 $C6 $C6 $83 $38 $C6 $CE $87 $30 $CE $DC $8F $20 $DC $88 $8F $70 $88 $AC $AF $50 $8C $AE $AF $50 $86 $FF $FE $01 $83
; Tile index $012
.db $FF $7F $80 $FF $FF $7F $80 $C0 $F0 $70 $8F $EF $F0 $30 $CF $EF $F8 $38 $C7 $F7 $D8 $38 $C7 $D7 $DF $3F $C0 $D8 $EF $1F $E0 $EF
; Tile index $013
.db $E7 $E6 $19 $DB $C7 $C6 $39 $3B $0E $0F $F0 $F6 $0C $0F $F0 $F4 $1C $1F $E0 $EC $18 $1F $E0 $E8 $F8 $FF $00 $18 $F1 $FE $01 $F1
; Tile index $014
.db $E3 $63 $9C $DD $E1 $61 $9E $DE $F0 $70 $8F $EF $F0 $30 $CF $EF $F8 $38 $C7 $F7 $D8 $38 $C7 $D7 $DF $3F $C0 $D8 $EF $1F $E0 $EF
; Tile index $015
.db $C6 $C7 $38 $BA $86 $87 $78 $7A $0E $0F $F0 $F6 $0C $0F $F0 $F4 $1C $1F $E0 $EC $18 $1F $E0 $E8 $F8 $FF $00 $18 $F1 $FE $01 $F1
; Tile index $016
.db $E6 $67 $98 $DA $E6 $67 $98 $DA $E6 $67 $98 $DA $E6 $67 $98 $DA $E6 $67 $98 $DA $E6 $67 $98 $DA $FE $7F $80 $C2 $FE $7F $80 $FE
; Tile index $017
.db $81 $7E $81 $81 $83 $7C $83 $83 $83 $7C $83 $83 $87 $78 $87 $87 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $018
.db $FF $FE $01 $FF $FF $FE $01 $03 $07 $06 $F9 $FB $07 $06 $F9 $FB $06 $07 $F8 $FA $06 $07 $F8 $FA $FE $FF $00 $02 $FE $FF $00 $FE
; Tile index $019
.db $C7 $C6 $39 $BB $C7 $C6 $39 $BB $C6 $C7 $38 $BA $C6 $C7 $38 $BA $C6 $C7 $38 $BA $C6 $C7 $38 $BA $FE $FF $00 $82 $FE $FF $00 $FE
; Tile index $01A
.db $E0 $1F $E0 $E0 $F0 $0F $F0 $F0 $F0 $0F $F0 $F0 $F8 $07 $F8 $F8 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $01B
.db $01 $FE $01 $01 $03 $FC $03 $03 $03 $FC $03 $03 $07 $F8 $07 $07 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $01C
.db $C0 $3F $C0 $C0 $C0 $3F $C0 $C0 $C0 $3F $C0 $C0 $C0 $3F $C0 $C0 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $01D
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF
; Tile index $01E
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $1F $E0 $FF $FF $04 $FB $FF $FF $04 $FB $FF $FF $04 $FB $FF $FF $04 $FB $FF $FF $00 $FF $FF
; Tile index $01F
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $44 $BB $FF $FF $6C $93 $FF $FF $54 $AB $FF $FF $44 $BB $FF $FF $44 $BB $FF $FF $00 $FF $FF
; Tile index $020
.db $FF $81 $7E $FF $FF $C3 $3C $FF $FF $42 $3C $FF $FF $66 $18 $FF $7E $24 $99 $7E $7E $3C $81 $7E $BD $00 $42 $BD $C3 $81 $3C $C3
; Tile index $021
.db $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6
; Tile index $022
.db $66 $C3 $18 $66 $66 $C3 $18 $66 $66 $C3 $18 $66 $66 $C3 $18 $66 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6
; Tile index $023
.db $67 $C2 $19 $67 $66 $C3 $18 $66 $66 $C3 $18 $66 $66 $C3 $18 $66 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $E6 $43 $98 $E6
; Tile index $024
.db $67 $C2 $19 $67 $67 $C2 $19 $67 $66 $C3 $18 $66 $66 $C3 $18 $66 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $FE $43 $80 $FE $FE $7F $80 $FE
; Tile index $025
.db $E6 $C3 $18 $E6 $C6 $83 $38 $C6 $CE $87 $30 $CE $DC $8F $20 $DC $D8 $8F $20 $D8 $DC $8F $20 $DC $CE $87 $30 $CE $E7 $C2 $19 $E7
; Tile index $026
.db $E7 $43 $98 $E7 $F3 $61 $8C $F3 $F1 $20 $CE $F1 $FC $30 $C3 $FC $DF $3C $C0 $DF $C7 $3F $C0 $C7 $E1 $1F $E0 $E1 $E0 $1F $E0 $E0
; Tile index $027
.db $C0 $3F $C0 $C0 $C0 $BF $40 $C0 $E0 $FF $00 $E0 $F8 $3F $00 $F8 $3F $0C $C3 $3F $CF $04 $33 $CF $CF $C6 $31 $CF $67 $C2 $19 $67
; Tile index $028
.db $E7 $43 $98 $E7 $E7 $40 $98 $E7 $E0 $40 $9F $E0 $E0 $40 $9F $E0 $C0 $40 $BF $C0 $DC $5C $A3 $C0 $D8 $58 $A7 $C0 $FF $7F $80 $C3
; Tile index $029
.db $E6 $C3 $18 $E6 $E6 $03 $18 $E6 $06 $03 $F8 $06 $06 $03 $F8 $06 $02 $03 $FC $02 $3A $3B $C4 $02 $1A $1B $E4 $02 $FE $FF $00 $C2
; Tile index $02A
.db $E7 $42 $99 $E7 $E7 $42 $99 $E7 $E6 $43 $98 $E6 $E6 $43 $98 $E6 $C2 $43 $BC $C2 $DA $5B $A4 $C2 $DA $5B $A4 $C2 $FE $7F $80 $C2
; Tile index $02B
.db $FE $7F $80 $FE $FE $43 $80 $FE $E7 $42 $99 $E7 $E7 $42 $99 $E7 $C3 $42 $BC $C2 $DB $5A $A4 $C2 $DB $5A $A4 $C2 $FF $7E $80 $C2
; Tile index $02C
.db $67 $C2 $19 $67 $67 $C2 $19 $67 $66 $C3 $18 $66 $E6 $43 $98 $E6 $C2 $43 $BC $C2 $DA $5B $A4 $C2 $DA $5B $A4 $C2 $FE $7F $80 $C2
; Tile index $02D
.db $66 $E7 $18 $5A $66 $E7 $18 $5A $66 $E7 $18 $5A $66 $E7 $18 $5A $E6 $67 $98 $DA $E6 $67 $98 $DA $FE $7F $80 $C2 $FE $7F $80 $FE
; Tile index $02E
.db $E6 $E7 $18 $DA $C6 $C7 $38 $BA $CE $CF $30 $B6 $CC $CF $30 $B4 $DC $DF $20 $AC $D8 $DF $20 $A8 $F8 $FF $00 $98 $F1 $FE $01 $F1
; Tile index $02F
.db $FF $7E $81 $FF $FF $7E $81 $C3 $E6 $67 $98 $DA $E6 $67 $98 $DA $E6 $67 $98 $DA $E6 $67 $98 $DA $FE $7F $80 $C2 $FE $7F $80 $FE
; Tile index $030
.db $BF $40 $3F $BF $BF $40 $3F $BF $BF $40 $27 $BF $BB $44 $23 $BB $B3 $4C $33 $B3 $80 $40 $3F $80 $7F $80 $00 $7F $00 $7F $00 $00
; Tile index $031
.db $C0 $3F $C0 $C0 $C0 $3F $C0 $C0 $C0 $3F $C0 $C0 $C0 $3F $C0 $C0 $FF $00 $FF $FF $00 $00 $FF $00 $FF $00 $00 $FF $00 $FF $00 $00
; Tile index $032
.db $E0 $1F $E0 $E0 $F0 $0F $F0 $F0 $F0 $0F $F0 $F0 $F8 $07 $F8 $F8 $FF $00 $FF $FF $00 $00 $FF $00 $FF $00 $00 $FF $00 $FF $00 $00
; Tile index $033
.db $01 $FE $01 $01 $03 $FC $03 $03 $03 $FC $03 $03 $07 $F8 $07 $07 $FF $00 $FF $FF $00 $00 $FF $00 $FF $00 $00 $FF $00 $FF $00 $00
; Tile index $034
.db $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $00 $FF $00 $00 $FF $00 $FF $00 $00
; Tile index $035
.db $81 $7E $81 $81 $83 $7C $83 $83 $83 $7C $83 $83 $87 $78 $87 $87 $FF $00 $FF $FF $00 $00 $FF $00 $FF $00 $00 $FF $00 $FF $00 $00
; Tile index $036
.db $FA $01 $FC $FA $FA $01 $FC $FA $FA $01 $CC $FA $F2 $09 $C4 $F2 $E2 $19 $E4 $E2 $02 $01 $FC $02 $FC $02 $00 $FC $00 $FC $00 $00
