; Tile index $000
.db $FF $00 $00 $00 $00 $00 $11 $EE $44 $44 $BB $00 $DE $DE $21 $00 $2A $7F $80 $00 $40 $DA $25 $00 $24 $EF $10 $00 $96 $BF $40 $00
; Tile index $001
.db $5A $FE $01 $00 $45 $5F $A0 $00 $10 $F6 $09 $00 $95 $DF $20 $00 $42 $EB $14 $00 $38 $7E $81 $00 $27 $EF $10 $00 $48 $7D $82 $00
; Tile index $002
.db $FF $00 $00 $00 $00 $00 $22 $DD $52 $52 $AD $00 $B5 $BD $42 $00 $AA $FF $00 $00 $40 $ED $12 $00 $32 $FB $04 $00 $88 $DF $20 $00
; Tile index $003
.db $0A $AE $51 $00 $A0 $FD $02 $00 $C9 $EF $10 $00 $24 $BD $42 $00 $05 $D7 $28 $00 $90 $FE $01 $00 $08 $DB $24 $00 $63 $6F $90 $00
; Tile index $004
.db $FC $00 $B2 $01 $B4 $00 $08 $43 $B2 $00 $04 $49 $96 $00 $20 $49 $94 $40 $00 $2B $D0 $04 $81 $2A $C8 $04 $A1 $12 $C0 $21 $98 $06
; Tile index $005
.db $E0 $19 $C4 $02 $E8 $04 $C1 $12 $D4 $00 $81 $2A $D4 $00 $A0 $0B $C6 $20 $80 $19 $E0 $10 $C8 $07 $F0 $0C $E2 $01 $FC $03 $F0 $00
; Tile index $006
.db $7D $80 $38 $02 $79 $80 $12 $04 $11 $22 $C4 $08 $33 $44 $81 $08 $43 $84 $09 $30 $87 $00 $33 $48 $03 $A0 $59 $04 $21 $DA $04 $00
; Tile index $007
.db $FB $04 $01 $00 $5F $80 $01 $20 $55 $80 $00 $2A $01 $42 $A8 $14 $03 $18 $A5 $40 $19 $24 $42 $80 $3D $42 $98 $00 $7F $80 $3D $00
; Tile index $008
.db $86 $7F $86 $7B $3F $FC $3F $F8 $7F $FC $7F $F8 $7F $FC $7F $F8 $FF $FC $FF $70 $FC $73 $FC $03 $70 $8F $70 $8F $77 $FF $77 $9F
; Tile index $009
.db $F7 $9F $F7 $0F $9F $6F $9F $63 $7F $F7 $7F $E0 $FF $F8 $FF $F0 $FF $FB $FF $60 $FF $77 $FF $03 $FF $00 $7F $00 $FF $00 $00 $00
; Tile index $00A
.db $6F $D8 $6C $98 $DF $BC $DE $38 $DF $BC $DE $38 $7F $DC $7E $98 $7F $EC $7E $C8 $FF $EC $FE $C0 $FF $EC $FE $C0 $FF $E0 $FE $C0
; Tile index $00B
.db $EF $DC $EE $98 $DF $BC $DE $38 $DF $BC $DE $38 $BF $7C $BE $78 $FF $78 $FE $30 $FF $B8 $FE $00 $FF $00 $FC $00 $FF $00 $00 $00
; Tile index $00C
.db $FF $00 $00 $00 $E7 $78 $67 $1F $FD $0E $7D $07 $DD $3E $7D $0F $DD $3E $7D $0F $DD $3E $7D $0F $DD $3E $7D $0F $DD $3E $7D $0F
; Tile index $00D
.db $DD $3E $7D $0F $DD $3E $7D $0F $DD $3E $7D $0F $DD $3E $7D $0F $DD $3E $7D $0F $DD $3E $7D $0F $FF $00 $00 $00 $FF $00 $C0 $00
; Tile index $00E
.db $FF $00 $00 $00 $E0 $1F $E0 $FF $7F $F0 $7F $C0 $3B $FF $3F $F0 $3B $FF $3F $F0 $3B $FF $3F $F0 $3B $FF $3F $F0 $3B $FF $3F $F0
; Tile index $00F
.db $3B $FF $3F $F0 $3B $FF $3F $F0 $3B $FF $3F $F0 $3B $FF $3F $F0 $3B $FF $3F $F0 $3B $FF $3F $F0 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $010
.db $FF $00 $00 $00 $00 $FF $00 $FF $FF $00 $FF $00 $F8 $FF $FF $00 $F8 $FF $FF $00 $F8 $FF $FF $00 $F8 $FF $FF $00 $F8 $FF $FF $00
; Tile index $011
.db $F8 $FF $FF $00 $F8 $FF $FF $00 $F8 $FF $FF $00 $F8 $FF $FF $00 $F8 $FF $FF $00 $F8 $FF $FF $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $012
.db $FF $00 $00 $00 $7F $FE $7E $80 $FF $00 $FC $00 $7F $80 $FC $00 $7F $80 $FC $00 $7F $80 $FC $00 $7F $80 $FC $00 $7F $80 $FC $00
; Tile index $013
.db $7F $80 $FC $00 $7F $80 $FC $00 $7F $80 $FC $00 $7F $80 $FC $00 $7F $80 $FC $00 $7F $80 $FC $00 $FF $00 $00 $00 $FF $00 $03 $00
; Tile index $014
.db $F7 $0F $DF $00 $F7 $0F $DF $00 $F7 $0F $DF $00 $F7 $0F $DF $00 $F7 $0F $DF $00 $F7 $0F $DF $00 $F7 $0F $DF $00 $F7 $0F $DF $00
; Tile index $015
.db $5D $BF $5F $F8 $5D $BF $5F $F8 $5D $BF $5F $F8 $5D $BF $5F $F8 $5D $BF $5F $F8 $5D $BF $5F $F8 $5D $BF $5F $F8 $5D $BF $5F $F8
; Tile index $016
.db $E1 $FE $FF $00 $E1 $FE $FF $00 $E1 $FE $FF $00 $E1 $FE $FF $00 $E1 $FE $FF $00 $E1 $FE $FF $00 $E1 $FE $FF $00 $E1 $FE $FF $00
; Tile index $017
.db $FF $00 $F3 $00 $FF $00 $F3 $00 $FF $00 $F3 $00 $FF $00 $F3 $00 $FF $00 $F3 $00 $FF $00 $F3 $00 $FF $00 $F3 $00 $FF $00 $F3 $00
; Tile index $018
.db $FF $00 $00 $00 $FF $40 $7F $00 $E0 $5F $7F $00 $BF $5F $3F $40 $BF $7F $3F $5F $FF $3F $7F $7F $C0 $3F $40 $7F $FF $00 $7F $7F
; Tile index $019
.db $C0 $3F $40 $7F $E0 $3F $60 $7F $FF $3F $7F $5F $BF $7F $3F $5F $BF $5F $3F $40 $A0 $5F $3F $40 $BF $5F $3F $40 $BF $5F $3F $40
; Tile index $01A
.db $FF $00 $01 $00 $FF $00 $FC $00 $03 $FC $FC $00 $FF $FC $FC $00 $FF $FC $FC $FC $FF $FC $FC $FC $03 $FC $00 $FC $FF $00 $FC $FC
; Tile index $01B
.db $03 $FC $00 $FC $03 $FC $00 $FC $FF $FC $FC $FC $FF $FC $FC $FC $FF $FC $FC $00 $03 $FC $FC $00 $FF $FC $FC $00 $FF $FC $FC $00
; Tile index $01C
.db $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $FF $00 $00 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $01D
.db $00 $FF $00 $FF $FF $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $FF $FF $FF $FF $FF $FF $FF $00 $FF $FF $FF $00 $00 $FF $FF $00
; Tile index $01E
.db $FF $07 $DF $00 $FF $07 $1F $00 $FF $07 $EF $00 $0F $F7 $F7 $00 $FF $FB $FB $00 $FF $FB $FB $00 $FF $FD $FD $FC $FF $FD $FD $FC
; Tile index $01F
.db $03 $FD $01 $FC $FD $02 $FC $FE $01 $FE $00 $FE $01 $FE $00 $FE $FF $FE $FE $FE $FF $FE $FE $00 $FF $FE $FE $00 $01 $FE $FE $00
; Tile index $020
.db $BF $5F $3F $40 $BF $5F $3F $40 $BF $5F $3F $40 $BF $5F $3F $40 $BF $5F $3F $40 $A0 $5F $3F $40 $A0 $5F $3F $40 $A0 $5F $3F $40
; Tile index $021
.db $A0 $5F $3F $40 $FF $40 $7F $00 $FF $40 $7F $00 $FF $40 $7F $00 $FF $40 $7F $00 $FF $40 $7F $00 $FF $40 $40 $00 $FF $00 $00 $00
; Tile index $022
.db $FF $FC $FC $00 $FF $FC $FC $00 $FF $FC $FC $00 $FF $FC $FC $00 $FF $FC $FC $00 $03 $FC $FC $00 $03 $FC $FC $00 $03 $FC $FC $00
; Tile index $023
.db $03 $FC $FC $00 $FF $00 $FC $00 $FF $00 $FC $00 $FF $00 $FC $00 $FF $00 $FC $00 $FF $00 $FC $00 $FF $00 $00 $00 $FF $00 $01 $00
; Tile index $024
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $FF $00
; Tile index $025
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $FF $00
; Tile index $026
.db $FF $FE $FE $00 $FF $FE $FE $00 $FF $FE $FE $00 $01 $FE $FE $00 $01 $FE $FE $00 $03 $FC $FE $00 $07 $F8 $FE $00 $FF $01 $FD $00
; Tile index $027
.db $FF $01 $FD $00 $FF $01 $FD $00 $FF $03 $FB $00 $FF $03 $FB $00 $FF $07 $F7 $00 $FF $07 $07 $00 $FF $07 $0F $00 $FF $07 $DF $00
; Tile index $028
.db $FF $00 $00 $00 $FF $00 $FF $FF $FF $00 $FF $FF $71 $00 $FF $FF $A2 $00 $FF $7D $D7 $00 $FF $28 $FF $00 $FF $00 $FF $00 $C3 $00
; Tile index $029
.db $FF $00 $00 $00 $FF $00 $3E $00 $6E $00 $DD $91 $3D $00 $EB $C3 $98 $00 $F7 $E7 $0C $00 $FB $F3 $06 $00 $FD $F9 $63 $00 $FE $9C
; Tile index $02A
.db $FF $00 $00 $00 $FF $00 $FF $FF $FF $00 $FF $FF $83 $00 $FF $FF $00 $00 $FF $FF $39 $00 $FF $C6 $FF $00 $FF $00 $FF $00 $C3 $00
; Tile index $02B
.db $FF $00 $00 $00 $FF $00 $7C $00 $7E $00 $BB $81 $BC $00 $D7 $C3 $19 $00 $EF $E7 $33 $00 $DF $CF $66 $00 $BF $9F $CC $00 $7F $3F
; Tile index $02C
.db $0F $00 $00 $0F $3F $00 $0F $3F $7F $00 $3F $7F $79 $00 $3F $7F $F0 $00 $7F $FF $E0 $00 $7F $FF $E1 $00 $7F $FE $E3 $00 $7F $FC
; Tile index $02D
.db $F3 $00 $7F $FC $F7 $00 $7F $F8 $F7 $00 $7E $F9 $E7 $00 $7E $F9 $EF $00 $7E $F1 $EF $00 $7E $F1 $E7 $00 $7E $F9 $F7 $00 $7E $F9
; Tile index $02E
.db $E7 $00 $7E $F9 $E7 $00 $7E $F9 $E7 $00 $7E $F9 $F7 $00 $7E $F9 $F7 $00 $7E $F9 $F7 $00 $7E $F9 $F7 $00 $7E $F9 $E7 $00 $7E $F9
; Tile index $02F
.db $F3 $00 $7F $FC $E7 $00 $7F $F8 $E7 $00 $7E $F9 $E7 $00 $7E $F9 $E7 $00 $7E $F9 $E7 $00 $7E $F9 $F7 $00 $7E $F9 $F7 $00 $7E $F9
; Tile index $030
.db $C2 $00 $7F $BF $F1 $00 $BF $4F $7D $00 $DF $A3 $3E $00 $EF $D1 $1F $00 $F7 $E8 $0F $00 $FB $F4 $07 $00 $FD $FA $47 $00 $FE $B9
; Tile index $031
.db $1F $00 $FE $E1 $3F $00 $FD $C2 $7E $00 $F3 $8D $7C $00 $E7 $9B $F9 $00 $CF $37 $F3 $00 $DF $2F $E6 $00 $BF $5F $CC $00 $7F $BF
; Tile index $032
.db $C7 $00 $FE $F9 $C7 $00 $FE $F9 $E7 $00 $FE $F9 $47 $00 $FE $F9 $9E $00 $FD $63 $FF $00 $FD $02 $FF $00 $F1 $0E $F7 $00 $0E $F9
; Tile index $033
.db $F2 $00 $7F $8F $FA $00 $BF $45 $7D $00 $CF $B2 $BE $00 $E7 $D9 $5E $00 $F3 $ED $2F $00 $FB $F4 $17 $00 $FD $FA $0B $00 $FE $FD
; Tile index $034
.db $91 $00 $FF $EE $50 $00 $FF $EF $08 $00 $FF $F7 $04 $00 $FF $FF $06 $00 $FF $FB $A2 $00 $FF $5D $D3 $00 $FF $2C $E5 $00 $FF $1E
; Tile index $035
.db $F0 $00 $00 $F0 $CC $00 $F0 $FC $8E $00 $FC $F2 $06 $00 $FC $FA $07 $00 $FE $F9 $37 $00 $FE $F9 $E7 $00 $FE $79 $E7 $00 $FE $79
; Tile index $036
.db $E7 $00 $FE $79 $E7 $00 $FE $79 $E7 $00 $7E $F9 $F7 $00 $7E $F9 $F7 $00 $7E $F9 $F7 $00 $7E $F9 $F7 $00 $7E $F9 $E7 $00 $7E $F9
; Tile index $037
.db $FB $00 $7F $FC $FF $00 $7F $FF $FF $00 $7F $FF $9E $00 $7F $FF $C1 $00 $BF $7E $F7 $00 $BF $48 $7F $00 $CF $B0 $3F $00 $F0 $CF
; Tile index $038
.db $FF $00 $FF $00 $FF $00 $FF $00 $F8 $00 $F8 $07 $F7 $07 $F0 $08 $F6 $07 $F1 $0B $EC $0C $E0 $17 $ED $0D $E0 $16 $ED $0D $E0 $16
; Tile index $039
.db $ED $0D $E0 $16 $ED $0D $E0 $16 $ED $0D $E0 $16 $ED $0D $E0 $16 $ED $0D $E0 $16 $F6 $07 $F1 $0B $F7 $07 $F0 $08 $FB $03 $F8 $04
; Tile index $03A
.db $FF $00 $FF $00 $FF $00 $FF $00 $1F $60 $7F $E0 $CF $F0 $3F $30 $CF $F0 $3F $30 $67 $F8 $9F $98 $67 $F8 $9F $98 $67 $F8 $9F $98
; Tile index $03B
.db $67 $F8 $9F $98 $67 $F8 $9F $98 $67 $F8 $9F $98 $67 $F8 $9F $98 $67 $F8 $9F $98 $CF $F0 $3F $30 $CF $F0 $3F $30 $9F $E0 $7F $60
; Tile index $03C
.db $FF $00 $00 $FF $FF $00 $7F $FF $D8 $00 $7F $E7 $D8 $00 $7F $FF $C0 $00 $7F $FF $C0 $00 $7F $FF $C3 $00 $7F $FC $C3 $00 $7F $FC
; Tile index $03D
.db $C3 $00 $7F $FC $C3 $00 $7F $FF $D8 $00 $7F $E7 $D8 $00 $7F $FF $C0 $00 $7F $FF $C0 $00 $7F $FF $FF $00 $7F $C0 $FF $00 $00 $FF
; Tile index $03E
.db $FF $00 $00 $FF $FF $00 $FF $FF $06 $00 $FF $F9 $07 $00 $FF $F9 $07 $00 $FF $FF $00 $00 $FF $FF $E0 $00 $FF $3F $E1 $00 $FF $3E
; Tile index $03F
.db $E1 $00 $FF $3E $E3 $00 $FF $FC $F3 $00 $FF $1C $F3 $00 $FF $1F $F0 $00 $FF $FF $00 $00 $FF $FF $FF $00 $FF $00 $FF $00 $00 $FF
; Tile index $040
.db $FF $00 $00 $FF $FF $00 $FF $FF $06 $00 $FF $F9 $06 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $C0 $00 $FF $7F
; Tile index $041
.db $C0 $00 $FF $7F $C0 $00 $FF $7F $C0 $00 $FF $7F $C7 $00 $FF $F9 $07 $00 $FF $F9 $07 $00 $FF $FF $FF $00 $FF $00 $FF $00 $00 $FF
; Tile index $042
.db $FF $00 $00 $FF $FF $00 $FE $FD $07 $00 $FE $F9 $07 $00 $FE $F9 $E7 $00 $FE $39 $E7 $00 $FE $39 $E7 $00 $FE $F9 $07 $00 $FE $F9
; Tile index $043
.db $07 $00 $FE $F9 $07 $00 $FE $F9 $3F $00 $FE $C1 $3F $00 $FE $C1 $3F $00 $FE $F9 $07 $00 $FE $F9 $FF $00 $FE $01 $FF $00 $00 $FF
; Tile index $044
.db $FF $00 $00 $FF $FF $00 $FF $FF $00 $00 $FF $FF $FF $00 $00 $FF $FF $00 $FF $00 $30 $00 $FF $CF $36 $00 $FF $CF $00 $00 $FF $FF
; Tile index $045
.db $07 $00 $FF $F8 $1B $00 $FF $FC $1B $00 $FF $FC $DC $00 $FF $3F $DC $00 $FF $3F $C0 $00 $FF $3F $0C $00 $FF $F3 $0C $00 $FF $F3
; Tile index $046
.db $FF $00 $00 $FF $FF $00 $FE $FF $01 $00 $FE $FF $FF $00 $00 $FF $FE $00 $FC $02 $0E $00 $FC $F2 $CE $00 $FC $F2 $0E $00 $FC $F2
; Tile index $047
.db $0E $00 $FC $F2 $0E $00 $FC $F2 $2E $00 $FC $D2 $2E $00 $FC $D2 $4E $00 $FC $F2 $6E $00 $FC $F2 $0E $00 $FC $F2 $EE $00 $FC $12
; Tile index $048
.db $00 $00 $FF $FF $06 $00 $FF $F9 $E6 $00 $FF $19 $DC $00 $FF $3F $DC $00 $FF $3F $00 $00 $FF $FF $06 $00 $FF $F9 $05 $00 $FF $FB
; Tile index $049
.db $03 $00 $FF $FF $0F $00 $FF $F3 $0C $00 $FF $F3 $60 $00 $FF $9F $F0 $00 $FF $9F $90 $00 $FF $FF $F6 $00 $FF $F9 $06 $00 $FF $F9
; Tile index $04A
.db $EF $00 $FC $13 $0F $00 $FD $F2 $0F $00 $FD $F2 $0F $00 $FC $F3 $3F $00 $FF $F0 $58 $00 $FF $BF $58 $00 $FF $BF $80 $00 $FF $FF
; Tile index $04B
.db $87 $00 $FF $F8 $87 $00 $FF $F8 $07 $00 $FF $F8 $60 $00 $FF $9F $67 $00 $FF $9F $67 $00 $FF $9F $00 $00 $FF $FF $06 $00 $FF $F9
; Tile index $04C
.db $FF $00 $FE $FD $83 $00 $FE $FD $93 $00 $FE $FD $A7 $00 $FE $FD $8B $00 $FE $FD $93 $00 $FE $FD $FF $00 $FE $01 $FF $00 $00 $FF
; Tile index $04D
.db $FF $00 $E5 $DA $3F $00 $EF $D7 $3F $00 $E7 $DC $7B $00 $EF $D4 $BA $00 $E7 $DD $3B $00 $EF $D4 $FB $00 $E7 $1C $FF $00 $00 $FF
; Tile index $04E
.db $FF $00 $00 $FF $F1 $00 $7E $FF $FF $00 $7E $C1 $B7 $00 $7E $C9 $AD $00 $7E $D3 $BB $00 $7E $C5 $BF $00 $7E $C1 $FF $00 $00 $FF
; Tile index $04F
.db $FF $00 $4F $BF $18 $00 $EF $FF $F9 $00 $EF $1F $7A $00 $EF $9F $D8 $00 $EF $3F $B9 $00 $EF $5F $FF $00 $EF $10 $FF $00 $00 $FF
